version: "3"

# Notes:
# - In bitcoind environment rpcauth, escape the dollar sign with a double dollar
# - ELECTRS_NETWORK=bitcoin means mainnet. The value must be either 'bitcoin', 'testnet' or 'regtest'.

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcauth=electrs:29b2fae539626e8bac1a1486de38164e$$32e907cec3853446590f0f5e794b3473640250c155d76bcbf0339a904f0b1cbf

  electrs:
    image: gradientskier/electrs:v0.9.9
    container_name: electrs
    entrypoint: electrs --log-filters=INFO --index-batch-size=10 --timestamp --db-dir /home/user/db
    restart: unless-stopped
    healthcheck:
      disable: true
    ports:
      - "127.0.0.1:50001:50001"
    volumes:
      - "bitcoin_datadir:/root/.bitcoin:ro"
      - "electrs_datadir:/home/user"
      - "./electrs.toml:/etc/electrs/config.toml:ro"
    environment:
      ELECTRS_NETWORK: ${ELECTRS_NETWORK:?Please specify ELECTRS_NETWORK environment variable. The value must be either 'bitcoin', 'testnet' or 'regtest'.}
      ELECTRS_DAEMON_RPC_ADDR: bitcoind:43782
      ELECTRS_DAEMON_P2P_ADDR: bitcoind:39388
      ELECTRS_ELECTRUM_RPC_ADDR: 0.0.0.0:50001
    depends_on:
      - bitcoind

  # TODO to implement electrs encrypted server
  # Neet to recompile nginx with stream
  # https://github.com/tekn0ir/nginx-stream/blob/master/Dockerfile
  electrs-nginx:
    image: tekn0ir/nginx-stream
    container_name: electrs-nginx
    ports:
      - "50002:50002"
    volumes:
      - "./electrs.nginx.conf:/opt/nginx/stream.conf.d/electrs.conf:ro"
      - "nginx_certs:/opt/nginx/certs:ro"

volumes:
  electrs_datadir:

incompatible:
  - pruning
