version: "3"
# If you don't use Lightning Network, use opt-save-store-xxs instead
# This save about 8 years of block, your lightning node won't be able to see channel created 8 year since the time you start it.

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  bitcored:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
  dogecoind:
    environment:
      DOGECOIN_EXTRA_ARGS: prune=800000
  monacoind:
    environment:
      BITCOIN_EXTRA_ARGS: prune=800000
exclusive:
  - pruning