version: "3"

services:
  guacd:
    restart: unless-stopped
    image: guacamole/guacd:1.5.4
    # environment:
    #   GUACD_LOG_LEVEL: debug

  guacamole:
    restart: unless-stopped
    image: guacamole/guacamole:1.5.4
    environment:
      GUACAMOLE_HOME: /etc/guacamole
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    volumes:
      - "./guacamole/user-mapping.xml:/etc/guacamole/user-mapping.xml:ro"
    links:
      - guacd
    depends_on:
      - guacd

  btcpayserver:
    environment:
      BTCPAY_EXTERNALSERVICES: "Apache Guacamole:guacamole/#/?username=USERNAME&password=PASSWORD"
