- name: dphys-swapfile swapoff
  shell: dphys-swapfile swapoff
  changed_when: False

- name: Remove default swapfile if exists
  file:
    path: /var/swap
    state: absent

- name: Copy dphys-swapfile
  copy:
    src: dphys-swapfile
    dest: /etc/dphys-swapfile
    mode: '0644'
  register: copy_dphys_swapfile

- name: Create /var/lib/docker/opt if not exists
  file:
    path: /var/lib/docker/opt
    state: directory
    mode: '0755'
  when: copy_dphys_swapfile.changed

- name: Remove swapfile if exists
  file:
    path: /var/lib/docker/opt/swapfile
    state: absent
  when: copy_dphys_swapfile.changed

- name: dphys-swapfile setup
  shell: dphys-swapfile setup
  when: copy_dphys_swapfile.changed
  
- name: dphys-swapfile swapon
  shell: dphys-swapfile swapon
  changed_when: False

# - name: Set CONF_SWAPFILE
#   lineinfile:
#     path: /etc/dphys-swapfile
#     regexp: '^CONF_SWAPFILE='
#     line: CONF_SWAPFILE=/var/lib/docker/opt/swapfile

# - name: Set CONF_SWAPSIZE
#   lineinfile:
#     path: /etc/dphys-swapfile
#     regexp: '^CONF_SWAPSIZE='
#     line: CONF_SWAPSIZE=4096

# - name: Set CONF_MAXSWAP
#   lineinfile:
#     path: /etc/dphys-swapfile
#     regexp: '^CONF_MAXSWAP='
#     line: CONF_MAXSWAP=4096
