#
# ll
#

- name: Set ll alias
  lineinfile:
    path: "{{item}}"
    regexp: '^alias ll='
    line: alias ll='ls $LS_OPTIONS -lah'
  with_items:
    - "/root/.bashrc"
    - "/home/{{username}}/.bashrc"

- name: Install htop
  apt:
    name: ['htop']
    state: latest
