- name: Install ufw (firewall) and fail2ban (ban invalid ssh login attempts)
  apt:
    name: ['ufw', 'fail2ban']
    state: present

- debug:
    msg: "docker bridge = {{interface_docker_bridge}}, other interfaces = {{interfaces_host}}"

- template:
    src: ufw-lightning.j2
    dest: "/etc/ufw/applications.d/ufw-lightning"

- template:
    src: ufw-remote-desktop.j2
    dest: "/etc/ufw/applications.d/ufw-remote-desktop"

- template:
    src: ufw-wireguard.j2
    dest: "/etc/ufw/applications.d/ufw-wireguard"

- name: ufw default deny incoming
  community.general.ufw:
    state: enabled
    default: deny
    direction: incoming

- name: ufw default allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing

- name: ufw allow ssh
  community.general.ufw:
    rule: allow
    name: OpenSSH
    interface_in: "{{item}}"
  with_items:
    - "{{interfaces_host}}"

- name: ufw delete allow remote desktop
  community.general.ufw:
    rule: allow
    name: "RDP"
    interface_in: "{{item}}"
    delete: true
  with_items:
      - "{{interface_docker_bridge}}"
      - "{{interfaces_host}}"

- name: ufw allow http and https
  community.general.ufw:
    rule: allow
    name: "WWW Full"
    interface_in: "{{item}}"
    delete: true
  with_items:
      - "{{interfaces_host}}"

- name: ufw allow dns
  community.general.ufw:
    rule: allow
    name: "DNS"
    interface_in: "{{item}}"
    delete: true
  with_items:
      - "{{interfaces_host}}"

- name: ufw allow lightning
  community.general.ufw:
    rule: allow
    name: "Lightning"
    interface_in: "{{item}}"
    delete: true
  with_items:
      - "{{interfaces_host}}"

- name: ufw allow wireguard
  community.general.ufw:
    rule: allow
    name: "Wireguard"
    interface_in: "{{item}}"
  with_items:
      - "{{interfaces_host}}"

- name: Allow all wireguard proxies
  community.general.ufw:
    rule: allow
    port: "{{item.1.1.proxy_source}}"
    interface_in: "{{item.0}}"
    proto: tcp
  loop: "{{ interfaces_host | product(proxy_to_lightning_hosts|enumerate) | list }}"
