- name: Install requirements
  apt:
    name: ['wireguard']
    state: present

- name: Create a line in hosts file for each wireguard host
  lineinfile:
    path: /etc/hosts
    line: "{{item.client_ip}}  {{item.client_name}}"
  loop: "{{wireguard_hosts}}"

# Configure wireguard newtork

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{paths.rpi_vault}}"
    state: directory
    mode: '0700'

- name: Register if wireguard private key already exists on target host
  ansible.builtin.stat:
    path: "{{ paths.wireguard_keyfile }}"
  register: wireguard_register_stat_keyfile

- name: Generate wireguard private key
  ansible.builtin.shell: |
    touch {{paths.wireguard_keyfile}}
    chmod 400 {{paths.wireguard_keyfile}}
    wg genkey > {{paths.wireguard_keyfile}}
  args:
    executable: /bin/bash
  when: not wireguard_register_stat_keyfile.stat.exists

- name: Copy wg0 file
  template:
    src: wg0.conf.tmpl
    dest: "/etc/wireguard/wg0.conf"

- name: Copy postup.sh
  template:
    src: postup.sh.j2
    dest: "/etc/wireguard/postup.sh"
    mode: '0755'

- name: Copy postdown.sh
  template:
    src: postdown.sh
    dest: "/etc/wireguard/postdown.sh"
    mode: '0755'

- name: Start wireguard
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: yes
    daemon_reload: yes
