- name: Install inotify-tools
  apt: 
    name: ['inotify-tools']
    state: latest

- name: Create backups directory if it does not exist
  file:
    path: "{{paths.backups}}"
    state: directory
    mode: '0755'

- name: Install lnd-channels-backup systemd unit file
  template: 
    src: lnd-channels-backup.service 
    dest: /etc/systemd/system/lnd-channels-backup.service

- name: Start and enable lnd-channels-backup
  systemd: 
    name: lnd-channels-backup 
    state: restarted 
    enabled: yes
    daemon_reload: yes
