- debug: 
    msg: "mkcert will generate certificates for: {{ mkcert_hostnames }}"

- name: Install wipe and libnss3-tools
  apt: 
    name: ['wipe', 'libnss3-tools']
    state: present

# Create the new working dir

- name: Create mkcert working directory if it does not exist
  file:
    path: "{{mkcert_working_dir}}"
    state: directory
    mode: '0755'

# Download of mkcert
# sha256sum /usr/local/bin/mkcert
- name: Download mkcert
  get_url:
    url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-arm64
    checksum: sha256:43c4e3b9e7e6466d397b3d6e221788f83b5b91f826f1040240dbaddfc101ce33
    dest: /usr/local/bin/mkcert
    mode: '0755'
  when: ansible_architecture == "aarch64"

- name: Download mkcert
  get_url:
    url: https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
    checksum: sha256:6d31c65b03972c6dc4a14ab429f2928300518b26503f58723e532d1b0a3bbb52
    dest: /usr/local/bin/mkcert
    mode: '0755'
  when: ansible_architecture == "x86_64"

# Create the certificate

- name: Recreate mkcert working directory
  file:
    path: "{{mkcert_working_dir}}"
    state: directory
    mode: '0755'

- name: Remove current mkcert certificate file
  file: 
    path: "{{mkcert_certificate_file}}"
    state: absent

- name: Remove current mkcert key file
  file: 
    path: "{{mkcert_certificate_key_file}}"
    state: absent

- name: Create the mkcert certificates
  shell: |
    export CAROOT="{{mkcert_working_dir}}"
    mkcert
    mkcert -cert-file default.crt -key-file default.key {{mkcert_hostnames}}
  args:
    executable: /bin/bash
    chdir: "{{mkcert_working_dir}}"

# Wipe the private key, so that no other certificate can be generated with same key (SKIP)

# - name: Check that the root ca key exists
#   stat:
#     path: "{{mkcert_rootca_key}}"
#   register: mkcert_rootca_key_result

# - name: Wipe the root ca key
#   shell: |
#     wipe -f "{{mkcert_rootca_key}}"
#   args:
#     executable: /bin/bash
#     chdir: "{{mkcert_working_dir}}"
#   when: mkcert_rootca_key_result.stat.exists

# The certificate needs to be installed for the pi user

- name: "Create mkcert {{username}} directory if it does not exist"
  file:
    path: "/home/{{username}}/mkcert"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"
    mode: '0751'

- name: "Copy rootCA to {{username}} home folder"
  copy: 
    remote_src: True
    src: "{{mkcert_rootca}}"
    dest: "/home/{{username}}/mkcert/rootCA.pem"
    owner: "{{username}}"
    group: "{{username}}"

# Creates file in /usr/local/share/ca-certificates
# Creates symlink in /etc/ssl/certs
# Remove symlinks with sudo update-ca-certificates -f

- name: "Install the mkcert certificates for the {{username}} user"
  shell: |
    export CAROOT=/home/{{username}}/mkcert
    mkcert -install
  become: Yes
  become_user: "{{username}}"
  args:
    executable: /bin/bash

# Copy certificates to btcpayserver nginx

- name: Copy certificate to btcpayserver nginx
  copy: 
    remote_src: True
    src: "{{mkcert_certificate_file}}"
    dest: "/var/lib/docker/volumes/generated_nginx_certs/_data/default.crt"

- name: Copy certificate key to btcpayserver nginx
  copy: 
    remote_src: True
    src: "{{mkcert_certificate_key_file}}"
    dest: "/var/lib/docker/volumes/generated_nginx_certs/_data/default.key"

- name: Restart btcpayserver nginx container
  shell: docker restart nginx
  args:
    executable: /bin/bash
  ignore_errors: yes
