# Run with:
# ansible-playbook -i hosts debian_reverse_proxy.yml
# was
# ansible-playbook -i hosts --extra-vars  "@../../proxy_to_tor_hosts.yml" debian_reverse_proxy.yml

# proxies.yml
#
# wireguard_hosts:
#   - client_name: btcpaydev
#     client_ip: 10.200.200.2
#     client_pubkey: mO/e0dL7mvreXKxhAGfdskormU/C7/M25kTX4=
#
# proxy_to_tor_hosts:
#   - proxy_sink: something.domain.com
#     proxy_source: something.onion
#     email: email@domain.com
#   - proxy_sink: btcpaydev.domain.com
#     proxy_source: something.onion
#     email: email@domain.com
#
# proxy_to_clearnet_hosts:
#   - proxy_sink: something.domain.com
#     proxy_source: 10.200.200.2
#     email: email@domain.com
#
# proxy_to_lightning_hosts:
#   - proxy_sink: 9735
#     proxy_source: 10.200.200.2

# Automating the procedure described here
# https://docs.btcpayserver.org/Deployment/ReverseProxyToTor/#reverse-proxy-to-tor

- name: Configure reverse proxy to tor on a Debian 11

  hosts: localhost
  connection: local
  vars_files:
    - vars/versions.yml
    - vars/proxies.yml

  pre_tasks:
    - debug:
        msg: "wireguard_hosts = {{ wireguard_hosts }}"

    - debug:
        msg: "proxy_to_tor_hosts = {{ proxy_to_tor_hosts }}"

    - debug:
        msg: "proxy_to_clearnet_hosts = {{ proxy_to_clearnet_hosts }}"

    - debug:
        msg: "proxy_to_lightning_hosts = {{ proxy_to_lightning_hosts }}"

    - name: apt-get update
      apt:
        update_cache: yes

  roles:
    - role: ufw
    - role: wireguard-server
    # - role: nginx-reverse-proxy-to-tor
    # proxy_to_tor_hosts: "{{proxy_to_tor_hosts}}"

  tasks:
    # VERY IMPORTANT: Add swap if the proxy machine is resource limited.
    - name: set swap_file variable
      set_fact:
        swap_file: /swapfile1G.swap

    - name: check if swap file exists
      stat:
        path: "{{ swap_file }}"
      register: swap_file_check

    - name: create swap file
      command: fallocate -l 1G {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: set permissions on swap file
      file:
        path: "{{ swap_file }}"
        mode: 0600

    - name: format swap file
      command: mkswap {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: add to fstab
      lineinfile:
        dest: /etc/fstab
        regexp: "{{ swap_file }}"
        line: "{{ swap_file }} none swap sw 0 0"

    - name: turn on swap
      command: swapon -a

