# ansible-playbook -i hosts playbook_localhost_pre.yml

- name: Configure localhost (PRE)

  hosts: localhost
  connection: local

  vars_files:
    - vars/versions.yml

  pre_tasks:
    - debug:
        msg: "BTCPAY_HOST = {{ lookup('env','BTCPAY_HOST') }}"

    - name: apt-get update with allow-releaseinfo-change
      command:
        cmd: apt-get update --allow-releaseinfo-change

  roles:
    - ufw
    - utils
    - nosuspend

  tasks:
    - name: Install node system dependencies
      apt:
        name: ['jq']
        state: present
