# ansible-playbook -i hosts playbook_localhost_pre.yml

- name: Configure localhost (PRE)
  
  hosts: localhost
  connection: local

  pre_tasks:
    - debug: 
        msg: "BTCPAY_HOST = {{ lookup('env','BTCPAY_HOST') }}"

  tasks:
    - name: apt-get update with allow-releaseinfo-change
      command:
        cmd: apt-get update --allow-releaseinfo-change

