- name: Configure localhost (PRE)
  
  hosts: localhost
  connection: local

  pre_tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: Install node system dependencies
      apt: 
        name: ['jq']
        state: present
