- name: Configure localhost (PRE)
  
  hosts: localhost
  connection: local

  pre_tasks:
    - name: apt-get update with allow-releaseinfo-change
      command:
        cmd: apt-get update --allow-releaseinfo-change

    - name: Install node system dependencies
      apt: 
        name: ['jq']
        state: present
